### ISSUE TITLE
Will .parseFilesGlob accept an array of strings?

### ISSUE THREAD

**Issue by sabsaxo** [connectedcars/gettext-extractor#14]
It seems it only validates a non empty string ... but I could be wrong.

**Comment by lukasgeiter** [comment]
It does not. It uses [node-glob](https://github.com/isaacs/node-glob) which doesn't support an array of patterns. You can, however, create a set within your pattern:
```
.parseFilesGlob'{pattern1,pattern2}'
```
Discussion over at node-glob: isaacs/node-glob#217

You may also simply call `.parseFilesGlob` multiple times with different pattern:

```
extractor
    .createJsParser([ /* ... */ ])
    .parseFilesGlob('pattern1')
    .parseFilesGlob('pattern2');
```

**Comment by sabsaxo** [comment]
This seem somewhat manual. I'm iterating an array in a for loop ... but it seems I have to wrap the whole ...

```
extractor
    .creaJSParser([ … ])
    .creaHtmlParser([ … ])
```

… object in the loop. And not just the `.parseFilesGlob` part ... meaning I recreate parsers on the object for every file in the array ... seems clunky.

**Comment by lukasgeiter** [comment]
You can simply create the parser first and store it in a variable:

```
let jsParser = extractor.createJsParser([ /* ... */ ]);
for (let pattern of patterns) {
    jsParser.parseFilesGlob(pattern);
}
```

**Comment by lukasgeiter** [comment]
Alternatively, as mentioned before, combine them into a single pattern:

```
let pattern = '{' + patterns.join(',') + '}';
```

**Comment by sabsaxo** [comment]
Yeah, thanks.
