### ISSUE TITLE
Can I pass in an array of strings to this?

### ISSUE THREAD

**Issue by sabsaxo** [connectedcars/gettext-extractor#15]
Would be nice to be able to pass an array of strings to this, as I have more specific needs than just being able to point to a src directory.

I traverse modules for dependencies, and would like to be able to only extract strings from these files, as I tag them on my localizing service.

**Comment by lukasgeiter** [comment]
What do you mean by _this_? If you are referring to `parseFilesGlob` like in #14, I'm not sure it's a good idea  to add support for this when it's very easy to implement for a user of the library. Could you give me a code example of your use case?

**Comment by sabsaxo** [comment]
Well, I think there's plenty of good use cases. In our case we have a huge (and potentially even huger) app that can, and will, be split into smaller apps. We have the need to be able to keep the translations files at a minimum (for each part of the app that's loaded in the client at any given time). Therefore I use `konan` to give me the dependencies of a given module (as an array of strings) and I'd then like to pass that array on to – yes, the `parseFilesGlob`. I've been trying to use it in a for loop, but that doesn't seem to work (at least at the moment), but I still have to do further fiddling.

Right now, I do:
```
	...

	const konan = require('konan');
	let src = fs.readFileSync( module_path + 'index.js', 'utf8'); // Path to main module
	let requires = konan( src );

	...

	for ( let i = 0, l = requires.strings.length; i < l; i++) {
		let path_to_code_file = modules_path + requires.strings[i].replace('../', '') + '/**/*.@(ts|js|tsx|jsx)',
		    path_to_markup_file = modules_path + requires.strings[i].replace('../', '') + '/templates/*.@(html|htm|hbs)';

		jsParser.parseFilesGlob( path_to_code_file );

		markupParser.parseFilesGlob( path_to_markup_file );
	}

	...
```
And then saves to .pot file.

But I guess that `parseFilesGlob` isn't appending to itself on each iteration ... and from what I know at the moment I don't know how to get to the parsed stuff, to see if I could somehow concatenate it myself.

**Comment by sabsaxo** [comment]
Heh, turns out it actually does concatenate ; ).
