### ISSUE TITLE
Some issues with parse5

### ISSUE THREAD

**Issue by Xesenix** [connectedcars/gettext-extractor#17]
After updating to version 3.3.1 i get this errors when trying to build (it doesn't ocure for version 3.2.1).
```
node_modules/gettext-extractor/dist/html/parser.d.ts(4,35): error TS2694: Namespace '"path-to-project/node_modules/parse5/lib/index"' has no exported member 'DefaultTreeNode'.
node_modules/gettext-extractor/dist/html/parser.d.ts(5,39): error TS2694: Namespace '"path-to-project/node_modules/parse5/lib/index"' has no exported member 'DefaultTreeTextNode'.
node_modules/gettext-extractor/dist/html/parser.d.ts(6,38): error TS2694: Namespace '"path-to-project/node_modules/parse5/lib/index"' has no exported member 'DefaultTreeElement'.
```
one module where im using has this import:
```
import { GettextExtractor, JsExtractors } from 'gettext-extractor';
```
im using typescript version 2.8.3 for building with this command
```
tsc --module commonjs
```

**Comment by lukasgeiter** [comment]
In the latest version I've upgraded to version 5 of the parse5 library which seems to be the cause of your issue. Are you also compiling the dist files of this package? Because that's not really necessary since it's already compiled from TypeScript to JavaScript.

In any case, a minimal working example of the problem would greatly help in figuring out what's happening.

**Comment by Xesenix** [comment]
While creating minimal example I found out that this problem doesn't exist in typescript 2.9.2 nor 2.9.1 so the solution may be setting minimal required typescript version to 2.9.1

Also, the minimal example is just the file with import from `gettext-extractor` (v3.3.1) compiled with typescript v2.8.3 compiled as mentioned above.

**Comment by Xesenix** [comment]
hmm adding `@types/parse5@5.0.0` works for me but you are right that my project should use already compiled version of your library

Also minimal example is just typescript file with:
```
import { GettextExtractor, JsExtractors } from 'gettext-extractor';
```
parsed with
```
tsc --module commonjs
```
and tsconfig.json like this:
```
{
  "compilerOptions": {
    "moduleResolution": "node",
    "target": "es6",
    "module":"es6",
    "lib": ["es2015", "es2016", "es2017", "dom"],
    "strict": true,
    "sourceMap": true,
    "declaration": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "declarationDir": "dist/types",
    "outDir": "dist/lib",
    "types": [
      "node"
    ],
    "typeRoots": [
      "node_modules/@types"
    ]
  },
  "include": ["src"]
}
```
And no dependency on `parse5` becouse when you add dependency `"parse5": "^5.0.0"` problems doesn't appear anymore as instaling `parse5` also installs typedefininitions for it

edit:
it looks that its problem with my tsconfig it was missing `"skipLibCheck": true,` so sorry about that this issue probably can be closed (alternative is moving @types/parse5 to dependencies)

**Comment by lukasgeiter** [comment]
No worries 😉 

I'll consider moving it to dependencies. I didn't really want to install any packages that aren't absolutely necessary but maybe it would be a good idea...

**Comment by lukasgeiter** [comment]
FYI: I've moved the necessary @type packages to dependencies in v3.3.2
