### ISSUE TITLE
Problems extracting messages from a Vue app

### ISSUE THREAD

**Issue by paumoreno** [connectedcars/gettext-extractor#2]
Hi!

We are trying to extract messages from our app, which is built with Vue.js. We are using [vue-i18n](https://github.com/kazupon/vue-i18n) to handle the translations. Instead of passing a message ID like `homepage.welcome_message` to the translator function, we're passing the message itself to translate, in Spanish.

Our first attempt was to extract messages directly from our `.vue` [single file components](https://vuejs.org/v2/guide/single-file-components.html).

The parser successfully extracted some of the messages fron the `<template>` part (probably beacause of the similarity with JSX templates?). In the templates, translation functions are called as `{{$t('message')}}`. However, the extractor failed to match the functions from the `<script>` part.

Our second attempt was to run the message extractor against the built file (using Webpack). In the built JS file, the translation functions from the templates are compiled to the following method call:

```js
_vm.$t('message')
```
These ones are correctly matched, by using the factory for method calls as follows:

```js
JsExtractors.methodCall('_vm', '$t', {
    arguments: { text: 0 }
})
```

However, there are a couple of cases where we cannot match the generated method calls:

```js
_vue2.default.t('message')
```

which is the compiled call from our source files' `Vue.t('message')`, and

```js
this.$t('message')
```

which are the calls to the translator function inside our component instances.

Is there a way to use the built-in extractor function creator factories to correctly parse instances of `_vue2.default.t` (or, as a generalisation `<obj1>.<obj2>.<method>`), and `this.$t` (or `this.<method>`)?

Thanks!

**Comment by lukasgeiter** [comment]
This is currently not possible with the built-in extractor function. I'll try to improve flexibility and allow for such cases in the next feature release.

Until then you can accomplish your goal with a custom extractor function.
This should work for your two cases:

```javascript
extractor.createJsParser([
    (node, sourceFile, addMessage) => {
        if (node.kind === ts.SyntaxKind.CallExpression) {
            let callExpression = node;
            let matches = false;

            if (callExpression.expression.kind === ts.SyntaxKind.PropertyAccessExpression) {
                let propertyAccessExpression = callExpression.expression;

                // this.$t('message')
                if (propertyAccessExpression.name.text === '$t'
                    && propertyAccessExpression.expression.kind === ts.SyntaxKind.ThisKeyword) {
                    matches = true;
                }

                // _vue2.default.t('message')
                if (propertyAccessExpression.name.text === 't'
                    && propertyAccessExpression.expression.kind === ts.SyntaxKind.PropertyAccessExpression) {
                    propertyAccessExpression = propertyAccessExpression.expression;

                    if (propertyAccessExpression.name.text === 'default'
                        && propertyAccessExpression.expression.kind === ts.SyntaxKind.Identifier
                        && propertyAccessExpression.expression.text === '_vue2') {
                        matches = true;
                    }
                }
            }

            if (matches) {
                // extract text argument and add message
                let textArgument = callExpression.arguments[0];

                if (textArgument && textArgument.kind === ts.SyntaxKind.StringLiteral) {
                    addMessage({
                        text: textArgument.text
                    });
                }
            }
        }
    }
]);
```

You will have to import `ts` from the `typescript` package (that is a dependency of this package so it should already be installed)

> **Note:** This custom extractor only extracts the text (and the file reference, which is extracted automatically). No other message information and no comments.

Let me know if you need any help with the custom extractor function.

**Comment by paumoreno** [comment]
Thank you very much for your explanation and for the implementation of the extractor function! I'm now able to extract all the messages from our web app :smile:.

We're now polishing some edge cases, but I'm pretty sure we'll stick to gettext-extractor to manage the extraction of copies for our website.

I think that making the factories able to handle cases such as `this.<methodName>` via configuration file will add a lot of flexibility.

**Comment by lukasgeiter** [comment]
I just released version 2 which replaces the `functionCall` and `methodCall` factories with the much more flexible `JsExtractors.callExpression`. It also supports `this.<method>` and `<object>.<object>.<method>`

Your specific case can be implemented as:

```javascript
JsExtractors.callExpression(['_vm.$t', '[this].$t', '_vue2.default.t'], {
    arguments: {
        text: 0
    }
});
```

P.S. The new release also supports HTML (including embedded JavaScript). So you might want to give extracting directly from your sources another shot 😃

**Comment by paumoreno** [comment]
Nice! Sorry that I didn't have the time to test it until now. It really simplifies the message extraction logic.

However, with version 2.1.0 the extractor gets `$t` calls inside HTML comments:

```html
<!--<span>{{ $t('Usando Twitter') }}</span>-->
```

Should these messages be ignored or is it the intended behaviour?

**Comment by lukasgeiter** [comment]
Am I correct in assuming that this HTML is part of a vue single file component? That would mean the HTML is being picked up as JSX which doesn't understand HTML comments so it doesn't ignore them.
Have you manually set `scriptKind` to JSX? Otherwise I believe the parser defaults to non-JSX for an unknown file extension like `.vue`.

**Comment by paumoreno** [comment]
Yes, you are correct.

I now use parse5's `SAXParser` to extract the `<template>` and `<script>` sections and parse them individually using `parseString`. However, none of the possible values of `scriptKind` seem to handle HTML comments as I would expect.

This is the script I'm using to chop the .vue files and parse their sections independently:

```es6
const fs = require('fs')
const parse5 = require('parse5')
const gettext = require('gettext-extractor')
const GettextExtractor = gettext.GettextExtractor
const JsExtractors = gettext.JsExtractors

const extractor = new GettextExtractor()

const filename = './components/Test.vue'

const readStream = fs.createReadStream(filename, {
    encoding: 'utf8'
});

const parser = new parse5.SAXParser({locationInfo: true})

let depth = 0

const sectionLocations = {
    template: null,
    script: null
}

parser.on('startTag', (name, attrs, selfClosing, location) => {
    if (depth === 0) {
        console.log('start', name, location)

        if (name === 'template' || name === 'script') {
            sectionLocations[name] = {
                start: location.endOffset,
                line: location.line
            }
        }
    }
    depth++
});

parser.on('endTag', (name, location) => {
    depth--

    if (depth === 0) {
        console.log('end', name, location)

        if (name === 'template' || name === 'script') {
            sectionLocations[name].end = location.startOffset
        }
    }
})

readStream.on('open', () => {
    readStream.pipe(parser)
})

readStream.on('end', () => {
    console.log(sectionLocations)

    const content = fs.readFileSync(filename, {
        encoding: 'utf8'
    });


    const template = content.substr(sectionLocations.template.start, sectionLocations.template.end - sectionLocations.template.start)
    
    const script = content.substr(sectionLocations.script.start, sectionLocations.script.end - sectionLocations.script.start)
    
    extractor
        .createJsParser([
            JsExtractors.callExpression(['$t', '[this].$t'], {
                arguments: {
                    text: 0
                }
            })
        ])
        .parseString(template, filename, {
            lineNumberStart: sectionLocations.template.line,
            scriptKind: 4
        })
        .parseString(script, filename, {
            lineNumberStart: sectionLocations.script.line
        })

    extractor.savePotFile('./i18n/test.pot');

    extractor.printStats();

})

```

And this is a sample .vue file to test it:

```vue
<template>
    <div>
        <span>{{ $t("Capture me") }}</span>
        <!--<span>{{ $t("Don't capture me") }}</span>-->
    </div>
</template>

<script>
    export default {
        data() {
            return {
                items: [
                    {
                        title: this.$t('Copy in script')
                    },
                    {
                        title: this.$t('Another copy in script')
                    }
                ]
            }
        }
    };
</script>

<style lang="scss" rel="stylesheet/scss">

</style>
```

**Comment by lukasgeiter** [comment]
> However, none of the possible values of scriptKind seem to handle HTML comments as I would expect.

The reason for this is pretty simple. You are using the TypeScript parser to parse HTML. Because it supports JSX and is rather forgiving this works for some things, but it will never work perfectly.  
What you actually would have to do is use parse5 to parse the full template and check every element's content. Whenever you find JavaScript you would call `parseString`.

It would certainly be nice if the extractor would support this scenario, but I'm not quite sure if it's possible to implement this in a generic way. Because as you may know there are many more template syntaxes (DOM or string based)

In case I'll ever implement this, would the following features be enough to support vue templates?
1. Parse `template` element as HTML (already possible)
1. Specify a regex to capture JS from an elements content (something like `^\s*{{(.*)}}\s*$`)
1. Specify a list of attribute names from which the content should be treated as JS as well

**Comment by paumoreno** [comment]
I ended up implementing a script which parses the `template` and `script` sections according to their peculiarities:

https://gist.github.com/paumoreno/cdfa14942424e895168a269a2deef1f3

What I do, in a nutshell, is:

- Parse the `template` section and extract all the JS snippets along with their location, looking for data binding attributes (starting with `:`), event attributes (starting with `@`), other directive attribbutes (starting with `v-`) and interpolations in text nodes
- Add the entire `script` section as another JS snippet to parse
- Extract messages from these snippets using `parseString`

So now I can happily use your library without needing to compile my source, with the extra bonus that I have the correct source references in the `.pot` file :smiley:

Thanks for this great library!
