### ISSUE TITLE
Extract comments from HTML

### ISSUE THREAD

**Issue by wjdp** [connectedcars/gettext-extractor#30]
Hi, I'm looking at using this project with vue-gettext. That projects supports comments like:

```
<translate translate-comment="My comment for translators">Foo</translate>
```

I'd like to extract this comment, I'd imagine I'd configure like this:

```
HtmlExtractors.elementContent('translate', {
    attributes: {
        textPlural: 'translate-plural',
        context: 'translate-context',
        comment: 'translate-comment',
    }
}
```

Is this possible / feasible?

**Comment by lukasgeiter** [comment]
That should be quite simple to implement. I'll let you know once a release with that feature is out.

**Comment by wjdp** [comment]
Amazing, thanks @lukasgeiter

**Comment by lukasgeiter** [comment]
Version 3.5.0 with this feature is released. The example you provided should work without any other changes 🙂

**Comment by wjdp** [comment]
Whoa, that's fast! @lukasgeiter thank you very much for the great package and speedy delivery of this feature, almost too good! :grin:
