### ISSUE TITLE
Replace SyntaxKing by ScriptKind in the wiki API Reference

### ISSUE THREAD

**Issue by Hyzual** [connectedcars/gettext-extractor#33]
Hi !
I wanted to propose a PR but I couldn't fork the wiki. Anyway, it's only a small change request; `SyntaxKind` does not list JS or TS, `ScriptKind` does. Here's the diff below.

--- a/API Reference.md  
+++ b/API Reference.md  
@@ -296,12 +296,12 @@ The enum values can be imported from the `typescript` package. The available opt
 ```javascript
 const ts = require('typescript');
 
-ts.SyntaxKind.Unknown; // = 0
-ts.SyntaxKind.JS; // = 1
-ts.SyntaxKind.JSX; // = 2
-ts.SyntaxKind.TS; // = 3
-ts.SyntaxKind.TSX; // = 4
-ts.SyntaxKind.External; // = 5
+ts.ScriptKind.Unknown; // = 0
+ts.ScriptKind.JS; // = 1
+ts.ScriptKind.JSX; // = 2
+ts.ScriptKind.TS; // = 3
+ts.ScriptKind.TSX; // = 4
+ts.ScriptKind.External; // = 5
 ```

**Comment by lukasgeiter** [comment]
Thanks for reporting that error! It's fixed now.

**Comment by Hyzual** [comment]
Thanks !
Also thanks for sharing gettext-extractor, it's great !
