### ISSUE TITLE
No extraction sometimes

### ISSUE THREAD

**Issue by pooledge** [connectedcars/gettext-extractor#55]
I've posted it in the svelte-specific [fork](https://github.com/floratmin/gettext-extractor-svelte/issues/1), but quickly realisied I get same with a bare. Some strings do not get extracted as expected, so I've tried to narrow it down to the following:
```svelte
<script lang="ts">
    import { __ } from '$lib/i18n';
</script>

<!-- These will be extracted: -->
<div>{@html __('More Settings')}</div>
<button type="button" aria-label="{__('I agree')}">{__('I agree')}</button>

<!-- These won't: -->
{__('Settings')}
<div>{__('Other Settings')}</div>
<button type="button">{__('I still agree')}</button>
```

Parser and config:
```js
import { GettextExtractor, JsExtractors } from 'gettext-extractor';

let extractor = new GettextExtractor();

extractor
	.createJsParser([
		JsExtractors.callExpression('__', {
			arguments: {
				text: 0
			}
		})
	])
	.parseFilesGlob('src/**/Test.svelte');

extractor.savePotFile('./src/translations/source.pot');
extractor.printStats();
```

Did I miss something in the config?
Thanks in advance for looking into this!

**Comment by lukasgeiter** [comment]
Unfortunately svelte files are not supported. You say it's not a svelte specific problem, yet the example you show is clearly svelte code. I'm assuming the only reason some of them work is because the TypeScript parser tries to make the best of it and sometimes it works and sometimes it doesn't.

**Comment by pooledge** [comment]
Thank you, Lukas! So I'd be better off hacking into parser then, could you provide any special hints?

**Comment by lukasgeiter** [comment]
I would reopen your issue over at gettext-extractor-svelte, maybe someone there can help. Other than that, I don't have any hints sorry.
