### ISSUE TITLE
How do I wrap strings for translation?

### ISSUE THREAD

**Issue by sabsaxo** [connectedcars/gettext-extractor#6]
I guess I have to wrap strings that should be extracted in some way ( __("Translate this.") or the like ), right?

What will this extractor look for? Or where in the configuration can I set this ... if.

**Comment by sabsaxo** [comment]
I can produce nothing but:

```
  0 messages extracted
  --------------------------
  0 total usages
  0 files (0 with messages)
  0 message contexts
```

No matter what I specify as my gettext function.

Doing this: 
```
import Gettext from 'node-gettext';
const gt = new Gettext();
gt.gettext('Translate this');

```
I've tried to modify this bit, as I "guess" this is where I specify what to look for ... ?

```
JsExtractors.callExpression('getText', { ...
```
to

```
JsExtractors.callExpression('gt.gettext', { ...
```
Yep, totally wild guessing here …

**Comment by lukasgeiter** [comment]
To answer your first question, yes your strings need to be passed to a function call. This will allow you to actually replace them with the translated version during runtime.

The code sample you provided actually looks correct.  
But as you can see from the output (`0 files`), you haven't actually processed any source files. If you're using `parseFilesGlob` I would probably double check the pattern and make sure it actually matches your files.
In case you need more help please paste the full code of how you're configuring the extractor.

**Comment by sabsaxo** [comment]
Thanks, yes the path was part of the problem.
