### ISSUE TITLE
savePotFile() headers order

### ISSUE THREAD

**Issue by sinedied** [connectedcars/gettext-extractor#9]
I tried to add some headers using the `savePotFile(fileName, [headers])` method, it works well but the `"Content-Type: text/plain; charset=UTF-8\n"` header that is added automatically is at the bottom wheras it should be the first header.

Should be simple to fix :)

**Comment by lukasgeiter** [comment]
Why should it be the first header though? As far as I know the order of headers shouldn't matter at all?

**Comment by sinedied** [comment]
> Why should it be the first header though?

Because it defines the character encoding of the document, so any subsequent headers would be interpreted using this encoding.

That may not be the case, but I assumed that it worked like the charset meta in html: nothing forces you to put it first but it's a good practice so other headers may be interpreted properly.

AFAIK, all PO/POT files I have encountered in different projects always had this header first.

**Comment by lukasgeiter** [comment]
Fair enough. However, that's something that should actually be fixed in [pofile](https://github.com/rubenv/pofile).

As you have seen the headers are passed to the library as object which doesn't technically specify an order.

**Comment by sinedied** [comment]
> as object which doesn't technically specify an order

True, but because of the implementation of object map in NodeJS, when you iterate you object keys the order is kept as-is ;)

**Comment by lukasgeiter** [comment]
I'm aware of that, but the standard explicitly states one should not rely on the order of object properties so I'd rather not do that.  
Since this is far from a critical issue I encourage you to open an issue or PR on the pofile repo and see what they have to say about it.

**Comment by sinedied** [comment]
@lukasgeiter Sure I'll do that so it can be properly fixed. But until then, this PR fix it and is harmless (you even spare 1 line of code 😉 )
